/**
 * Creates the local Aurora Postgres cluster + master secret in Floci
 * (https://floci.io) and writes the connection details to `.env.local`.
 *
 * Usage: `pnpm test:floci:up` (starts Floci via docker compose, then runs this).
 */
import { writeFileSync } from 'node:fs'
import {
	CreateDBClusterCommand,
	DBClusterAlreadyExistsFault,
	DescribeDBClustersCommand,
	RDSClient,
} from '@aws-sdk/client-rds'
import {
	CreateSecretCommand,
	DescribeSecretCommand,
	ResourceExistsException,
	SecretsManagerClient,
} from '@aws-sdk/client-secrets-manager'

// biome-ignore lint/suspicious/noConsole: CLI script output
const log = console.log

const endpoint = process.env.AWS_ENDPOINT_URL ?? 'http://localhost:4566'
const region = process.env.AWS_DEFAULT_REGION ?? 'us-east-1'
const credentials = { accessKeyId: 'test', secretAccessKey: 'test' }

const clusterId = 'kysely-aws-test'
const dbName = 'kyselytest'
const username = 'postgres'
const password = 'postgres'

const rds = new RDSClient({ endpoint, region, credentials })
const secrets = new SecretsManagerClient({ endpoint, region, credentials })

try {
	await rds.send(
		new CreateDBClusterCommand({
			DBClusterIdentifier: clusterId,
			Engine: 'aurora-postgresql',
			MasterUsername: username,
			MasterUserPassword: password,
			DatabaseName: dbName,
			EnableHttpEndpoint: true,
		}),
	)
	log(`created cluster ${clusterId}`)
} catch (error) {
	if (!(error instanceof DBClusterAlreadyExistsFault)) throw error
	log(`cluster ${clusterId} already exists`)
}

const { DBClusters } = await rds.send(
	new DescribeDBClustersCommand({ DBClusterIdentifier: clusterId }),
)
const clusterArn = DBClusters?.[0]?.DBClusterArn
if (!clusterArn) throw new Error('cluster has no ARN')

const secretName = `${clusterId}/master`
let secretArn: string | undefined
try {
	const secret = await secrets.send(
		new CreateSecretCommand({
			Name: secretName,
			SecretString: JSON.stringify({ username, password }),
		}),
	)
	secretArn = secret.ARN
	log(`created secret ${secretArn}`)
} catch (error) {
	if (!(error instanceof ResourceExistsException)) throw error
	const secret = await secrets.send(
		new DescribeSecretCommand({ SecretId: secretName }),
	)
	secretArn = secret.ARN
	log(`secret ${secretArn} already exists`)
}
if (!secretArn) throw new Error('secret has no ARN')

const env = [
	'# generated by `pnpm test:floci:up`',
	`AWS_ENDPOINT_URL=${endpoint}`,
	`AWS_ACCESS_KEY_ID=${credentials.accessKeyId}`,
	`AWS_SECRET_ACCESS_KEY=${credentials.secretAccessKey}`,
	`CDK_DEPLOY_ACCOUNT=000000000000`,
	`CDK_DEPLOY_REGION=${region}`,
	'',
	`RDS_PG_DB_NAME=${dbName}`,
	`RDS_PG_CLUSTER_ARN=${clusterArn}`,
	`RDS_PG_MASTER_SECRET_ARN=${secretArn}`,
	'',
].join('\n')

writeFileSync('.env.local', env)
log('wrote .env.local')
